"""add receipt image link

Revision ID: 22dbc78da032
Revises: c52d0ca1f9bf
Create Date: 2019-01-31 19:34:03.041811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dbc78da032'
down_revision = 'c52d0ca1f9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('receipt_image_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'receipt_image_link')
    # ### end Alembic commands ###
