"""create project plastic map table

Revision ID: 61f38ea5d851
Revises: ada1700cd552
Create Date: 2018-09-30 21:23:11.690917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61f38ea5d851'
down_revision = 'ada1700cd552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project_plastic_map',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column(
            'plastic_type',
            postgresql.ENUM(
                'green_pet',
                'pet_light_blue',
                'brown_pet',
                'pet_non_food_clear',
                'pet_clear',
                name='plastic_type',
                create_type=False),
            nullable=False), sa.Column(
                'quantity', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['project.id'],
        ), sa.PrimaryKeyConstraint('project_id', 'plastic_type'))
    op.drop_column('project', 'plastic_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project',
        sa.Column(
            'plastic_types',
            postgresql.ARRAY(
                postgresql.ENUM(
                    'green_pet',
                    'pet_light_blue',
                    'brown_pet',
                    'pet_non_food_clear',
                    'pet_clear',
                    name='plastic_type')),
            autoincrement=False,
            nullable=True))
    op.drop_table('project_plastic_map')
    # ### end Alembic commands ###
