"""empty message

Revision ID: 661f4a8952de
Revises: 88db108f7a32
Create Date: 2019-03-14 21:12:10.924487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661f4a8952de'
down_revision = '88db108f7a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('podio_master_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'podio_master_id')
    # ### end Alembic commands ###
