"""empty message

Revision ID: 744c892cb5c6
Revises:
Create Date: 2018-07-19 20:13:32.590534

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '744c892cb5c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'projects', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('type', sa.Integer(), nullable=False),
        sa.Column('gdrive_link', sa.Integer(), nullable=False),
        sa.Column('shipping_terms', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('transaction_attributes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('data_type', sa.Text(), nullable=False),
                    sa.Column('is_required', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('user_attributes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('data_type', sa.Text(), nullable=False),
                    sa.Column('is_required', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'users', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stakeholder_id', sa.Integer(), nullable=False),
        sa.Column('phone_number', sa.String(length=15), nullable=True),
        sa.Column('email', sa.String(length=254), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('password', sa.Text(), nullable=False),
        sa.Column(
            'forgot_password_token', sa.String(length=10), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'cost_model', sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('wastepicker_sell_price', sa.Float(), nullable=False),
        sa.Column('wholesaler_purchase_price', sa.Float(), nullable=False),
        sa.Column('wholesaler_sell_price', sa.Float(), nullable=False),
        sa.Column('price_buoyancy', sa.Float(), nullable=False),
        sa.Column('wholesaler_exworks_price', sa.Float(), nullable=False),
        sa.Column('wholesaler_shipping_price', sa.Float(), nullable=False),
        sa.Column('wholesaler_delivered_price', sa.Float(), nullable=False),
        sa.Column('pfc_transaction_fee', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
        ), sa.PrimaryKeyConstraint('project_id'))
    op.create_table('projects_association',
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'],
                        ['projects.id'],
                    ), sa.ForeignKeyConstraint(
                        ['user_id'],
                        ['users.id'],
                    ))
    op.create_table(
        'transactions', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('from_user_id', sa.Integer(), nullable=False),
        sa.Column('to_user_id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('image', sa.String(length=255), nullable=False),
        sa.Column('sale_date', sa.DateTime(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['from_user_id'],
            ['users.id'],
        ), sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
        ), sa.ForeignKeyConstraint(
            ['to_user_id'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'user_values_int', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('attribute_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attribute_id'],
            ['user_attributes.id'],
        ), sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'user_values_text', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('attribute_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attribute_id'],
            ['user_attributes.id'],
        ), sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'transaction_parents',
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['transactions.id'],
        ), sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transactions.id'],
        ), sa.PrimaryKeyConstraint('transaction_id', 'parent_id'))
    op.create_table(
        'transaction_values_float',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('attribute_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attribute_id'],
            ['transaction_attributes.id'],
        ), sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transactions.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'transaction_values_int', sa.Column(
            'id', sa.Integer(), nullable=False),
        sa.Column('attribute_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attribute_id'],
            ['transaction_attributes.id'],
        ), sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transactions.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'transaction_values_text', sa.Column(
            'id', sa.Integer(), nullable=False),
        sa.Column('attribute_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['attribute_id'],
            ['transaction_attributes.id'],
        ), sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transactions.id'],
        ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_values_text')
    op.drop_table('transaction_values_int')
    op.drop_table('transaction_values_float')
    op.drop_table('transaction_parents')
    op.drop_table('user_values_text')
    op.drop_table('user_values_int')
    op.drop_table('transactions')
    op.drop_table('projects_association')
    op.drop_table('cost_model')
    op.drop_table('users')
    op.drop_table('user_attributes')
    op.drop_table('transaction_attributes')
    op.drop_table('projects')
    # ### end Alembic commands ###
