"""Initial table creation

Revision ID: a1b8a4cb1c13
Revises:
Create Date: 2018-08-09 01:24:03.011415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b8a4cb1c13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'project_type',
            sa.Enum('internal', 'external', name='project_type'),
            nullable=False),
        sa.Column(
            'plastic_types',
            postgresql.ARRAY(
                sa.Enum(
                    'green_pet',
                    'pet_light_blue',
                    'brown_pet',
                    'pet_non_food_clear',
                    'pet_clear',
                    name='plastic_type')),
            nullable=True),
        sa.Column(
            'meta_data',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'vendor', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'vendor_type',
            sa.Enum(
                'admin',
                'wastepicker',
                'dwcc',
                'wholesaler',
                'manufacturer',
                name='vendor_type'),
            nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'meta_data',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'dwcc_wastepicker_map',
        sa.Column('wastepicker_id', sa.Integer(), nullable=False),
        sa.Column('dwcc_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['dwcc_id'],
            ['vendor.id'],
        ), sa.ForeignKeyConstraint(
            ['wastepicker_id'],
            ['vendor.id'],
        ), sa.PrimaryKeyConstraint('wastepicker_id'),
        sa.UniqueConstraint('dwcc_id', 'wastepicker_id'))
    op.create_index(
        'IX_dwcc_wastepicker_map_dwcc_id',
        'dwcc_wastepicker_map', ['dwcc_id'],
        unique=False)
    op.create_table('project_vendor_map',
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('vendor_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'],
                        ['project.id'],
                    ), sa.ForeignKeyConstraint(
                        ['vendor_id'],
                        ['vendor.id'],
                    ), sa.PrimaryKeyConstraint('project_id', 'vendor_id'),
                    sa.UniqueConstraint('project_id', 'vendor_id'))
    op.create_index(
        'IX_project_vendor_map_project_id',
        'project_vendor_map', ['project_id'],
        unique=False)
    op.create_index(
        'IX_project_vendor_map_vendor_id',
        'project_vendor_map', ['vendor_id'],
        unique=False)
    op.create_table(
        'user', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.Binary(length=60), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column(
            'meta_data',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True),
        sa.ForeignKeyConstraint(
            ['vendor_id'],
            ['vendor.id'],
        ), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('email'))
    op.create_index('IX_user_email', 'user', [sa.text('lower(email)')])
    op.create_table('transaction', sa.Column(
        'id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('from_vendor_id', sa.Integer(), nullable=False),
                    sa.Column('to_vendor_id', sa.Integer(), nullable=False),
                    sa.Column('to_acknowledged', sa.Boolean(), nullable=False),
                    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
                    sa.Column('price', sa.Float(precision=2), nullable=False),
                    sa.Column('sale_date', sa.DateTime(), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['creator_id'],
                        ['user.id'],
                    ),
                    sa.ForeignKeyConstraint(
                        ['from_vendor_id'],
                        ['user.id'],
                    ), sa.ForeignKeyConstraint(
                        ['project_id'],
                        ['project.id'],
                    ), sa.ForeignKeyConstraint(
                        ['to_vendor_id'],
                        ['user.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'transaction_parent_map',
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['transaction.id'],
        ), sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transaction.id'],
        ), sa.PrimaryKeyConstraint('transaction_id', 'parent_id'),
        sa.UniqueConstraint('transaction_id', 'parent_id'))
    op.create_index(
        'IX_transaction_parent_map_transaction_id',
        'transaction_parent_map', ['transaction_id'],
        unique=False)
    op.create_table(
        'transaction_plastic_map',
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column(
            'plastic_type',
            sa.Enum(
                'green_pet',
                'pet_light_blue',
                'brown_pet',
                'pet_non_food_clear',
                'pet_clear',
                name='plastic_type'),
            nullable=False), sa.Column(
                'quantity', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(precision=2), nullable=True),
        sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transaction.id'],
        ), sa.PrimaryKeyConstraint('transaction_id', 'plastic_type'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_plastic_map')
    op.drop_index(
        'IX_transaction_parent_map_transaction_id',
        table_name='transaction_parent_map')
    op.drop_table('transaction_parent_map')
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_index(
        'IX_project_vendor_map_vendor_id', table_name='project_vendor_map')
    op.drop_index(
        'IX_project_vendor_map_project_id', table_name='project_vendor_map')
    op.drop_table('project_vendor_map')
    op.drop_index(
        'IX_dwcc_wastepicker_map_dwcc_id', table_name='dwcc_wastepicker_map')
    op.drop_table('dwcc_wastepicker_map')
    op.drop_table('vendor')
    op.drop_table('project')
    # ### end Alembic commands ###
